import praw
import urllib.request
import random
import os
import subprocess
import time


#A list of subreddits to download wallpapers from
r_list = ['earthporn', 'spaceporn', 'cityporn', 'skyporn', 'weatherporn', 
        'beachporn', 'wallpapers', 'waterporn', 'villageporn']

#The directory to hold the wallpapers
wallpaper_dir = 'DIR_TO_HOLD_WALLPAPERS'

#Client ID and Client Secret, generated by reddit
#More info can be found at https://github.com/reddit-archive/reddit/wiki/OAuth2
client_id = 'CLIENT_ID_HERE'
client_secret= 'CLIENT_SECRET_HERE'
user_agent = 'wallpaper downloader'

#The command used to change the wallpaper
cmd = "feh --bg-fill "

#The wait time between wallpaper changes
wait_time = 600

#If the directory doesn't exist, create it
if not os.path.isdir(wallpaper_dir):
    os.makedirs(wallpaper_dir)

#Endless loop
while True:
    #Try to make a connection to reddit
    try:
        reddit_connection = praw.Reddit(client_id=client_id,
            client_secret=client_secret,
            user_agent=user_agent)
        #Find a post for a wallpaper which hasn't been used 
        for post in reddit_connection.subreddit(random.choice(r_list)).hot(limit=20):
            #Check to make sure its a picture file
            if post.url.lower().endswith(('.png', '.jpg')):
                #Get the filename
                file_name = wallpaper_dir + os.path.basename(post.url)
                #Check if the wallpaper has been downloaded already
                if not os.path.exists(file_name):
                    #Download wallpaper
                    resp = urllib.request.urlretrieve(post.url, file_name)
                    #Change background
                    subprocess.call(cmd + file_name, shell=True)
                    #Close HTTP
                    resp.close()
                    #Wait
                    time.sleep(wait_time)
                    #Break the loop
                    break
    #If connection could not be made, use a wallpaper from wallpaper dir at random
    except:
        subprocess.call(cmd + wallpaper_dir + random.choice(os.listdir(wallpaper_dir)), shell=True)
        time.sleep(wait_time)
